-- AUTO-GENERATED by tools/generate-seed.mjs from src/seed/*.json
-- Do not edit by hand. To change master data:
--   1. edit the corresponding src/seed/*.json
--   2. run `node tools/generate-seed.mjs`
--   3. commit both the JSON and this regenerated file.
--
-- Applied after migrations on `supabase db reset`.

set search_path = public;

-- areas
insert into areas (name) values
  ('Sreekovil'),
  ('Namaskara Mandapam'),
  ('Homakundam'),
  ('Oottupura'),
  ('Kazhakam'),
  ('Prakaram'),
  ('Office'),
  ('Auditorium')
on conflict (name) do nothing;

-- verifiers
insert into verifiers (role, malayalam, sort_order) values
  ('Thantri', 'തന്ത്രി', 0),
  ('Melsanthi', 'മേൽശാന്തി', 1),
  ('Keezhsanthi', 'കീഴ്ശാന്തി', 2),
  ('Trustee', 'ട്രസ്റ്റി', 3),
  ('Secretary', 'സെക്രട്ടറി', 4),
  ('Store Keeper', 'സ്റ്റോർ കീപ്പർ', 5),
  ('Asst. Store Keeper', 'സഹ. സ്റ്റോർ കീപ്പർ', 6),
  ('Office In-charge', 'ഓഫീസ് ഇൻ-ചാർജ്', 7),
  ('Kazhakam Lead', 'കഴകം മേലാളൻ', 8)
on conflict (role) do update set
  malayalam = excluded.malayalam,
  sort_order = excluded.sort_order;

-- nakshatrams
insert into nakshatrams (name, malayalam, sort_order) values
  ('Ashwathi', 'അശ്വതി', 0),
  ('Bharani', 'ഭരണി', 1),
  ('Karthika', 'കാർത്തിക', 2),
  ('Rohini', 'രോഹിണി', 3),
  ('Makayiram', 'മകയിരം', 4),
  ('Thiruvathira', 'തിരുവാതിര', 5),
  ('Punartham', 'പുണർതം', 6),
  ('Pooyam', 'പൂയം', 7),
  ('Ayilyam', 'ആയില്യം', 8),
  ('Makam', 'മകം', 9),
  ('Pooram', 'പൂരം', 10),
  ('Uthram', 'ഉത്രം', 11),
  ('Atham', 'അത്തം', 12),
  ('Chithira', 'ചിത്തിര', 13),
  ('Chothi', 'ചോതി', 14),
  ('Vishakham', 'വിശാഖം', 15),
  ('Anizham', 'അനിഴം', 16),
  ('Thrikketta', 'തൃക്കേട്ട', 17),
  ('Moolam', 'മൂലം', 18),
  ('Pooradam', 'പൂരാടം', 19),
  ('Uthradam', 'ഉത്രാടം', 20),
  ('Thiruvonam', 'തിരുവോണം', 21),
  ('Avittam', 'അവിട്ടം', 22),
  ('Chathayam', 'ചതയം', 23),
  ('Pooruruttathi', 'പൂരുരുട്ടാതി', 24),
  ('Uthrattathi', 'ഉത്രട്ടാതി', 25),
  ('Revathi', 'രേവതി', 26)
on conflict (name) do update set
  malayalam = excluded.malayalam,
  sort_order = excluded.sort_order;

-- pooja_schedule
insert into pooja_schedule (time, name, malayalam) values
  ('04:30', 'Palli Unarthal', 'പള്ളിയുണർത്തൽ'),
  ('05:00', 'Nirmalyam', 'നിർമ്മാല്യം'),
  ('05:30', 'Abhishekam', 'അഭിഷേകം'),
  ('06:30', 'Usha Pooja', 'ഉഷ പൂജ'),
  ('08:00', 'Pantheeradi Pooja', 'പന്തീരടി പൂജ'),
  ('11:00', 'Ucha Pooja', 'ഉച്ച പൂജ'),
  ('17:30', 'Deeparadhana', 'ദീപാരാധന'),
  ('19:30', 'Athazha Pooja', 'അത്താഴ പൂജ'),
  ('20:30', 'Thripuka', 'തൃപ്പുക')
on conflict (time) do update set
  name = excluded.name,
  malayalam = excluded.malayalam;

-- vazhipadu_catalog
insert into vazhipadu_catalog (id, name, malayalam, price, area, items) values
  ('v1', 'Ganapathi Homam', 'ഗണപതി ഹോമം', 501, 'Homakundam', '[["Coconut",5],["Ghee",0.5],["Camphor",0.05],["Kumkum",0.02],["Akshatam",0.1]]'::jsonb),
  ('v2', 'Archana', 'അർച്ചന', 21, 'Sreekovil', '[["Flowers",0.05],["Camphor",0.005],["Kumkum",0.005],["Agarbathi",2]]'::jsonb),
  ('v3', 'Pushpanjali', 'പുഷ്പാഞ്ജലി', 51, 'Sreekovil', '[["Flowers",0.15],["Tulasi",0.05],["Camphor",0.01]]'::jsonb),
  ('v4', 'Neyyabhishekam', 'നെയ്യഭിഷേകം', 151, 'Sreekovil', '[["Ghee",0.25],["Flowers",0.1],["Camphor",0.02]]'::jsonb),
  ('v5', 'Bhagavathi Seva', 'ഭഗവതി സേവ', 751, 'Namaskara Mandapam', '[["Coconut",3],["Flowers",0.5],["Ghee",0.3],["Plantain",6],["Camphor",0.05]]'::jsonb),
  ('v6', 'Niramala', 'നിറമാല', 1101, 'Sreekovil', '[["Flowers",2],["Tulasi",0.5],["Camphor",0.05]]'::jsonb),
  ('v7', 'Annadanam (per plate)', 'അന്നദാനം', 25, 'Oottupura', '[["Rice",0.15],["Vegetables",0.2],["Ghee",0.02]]'::jsonb)
on conflict (id) do update set
  name = excluded.name, malayalam = excluded.malayalam,
  price = excluded.price, area = excluded.area, items = excluded.items;

-- inventory_items
insert into inventory_items
  (id, name, malayalam, unit, qty, opening, total_received, total_issued, reorder, unit_cost, type)
values
  ('i1', 'Coconut', 'നാളികേരം', 'nos', 240, 240, 0, 0, 50, 35, 'consumable'),
  ('i2', 'Ghee', 'നെയ്യ്', 'kg', 18.5, 18.5, 0, 0, 5, 620, 'consumable'),
  ('i3', 'Camphor', 'കർപ്പൂരം', 'kg', 2.4, 2.4, 0, 0, 0.5, 850, 'consumable'),
  ('i4', 'Kumkum', 'കുങ്കുമം', 'kg', 1.8, 1.8, 0, 0, 0.3, 480, 'consumable'),
  ('i5', 'Akshatam', 'അക്ഷതം', 'kg', 3.2, 3.2, 0, 0, 0.5, 90, 'consumable'),
  ('i6', 'Flowers', 'പുഷ്പം', 'kg', 6.5, 6.5, 0, 0, 2, 220, 'consumable'),
  ('i7', 'Tulasi', 'തുളസി', 'kg', 1.2, 1.2, 0, 0, 0.3, 180, 'consumable'),
  ('i8', 'Agarbathi', 'ചന്ദന തിരി', 'sticks', 480, 480, 0, 0, 100, 1.5, 'consumable'),
  ('i9', 'Plantain', 'നേന്ത്രപ്പഴം', 'nos', 36, 36, 0, 0, 12, 12, 'consumable'),
  ('i10', 'Rice', 'അരി', 'kg', 85, 85, 0, 0, 20, 55, 'consumable'),
  ('i11', 'Vegetables', 'പച്ചക്കറി', 'kg', 22, 22, 0, 0, 8, 60, 'consumable')
on conflict (id) do update set
  name = excluded.name, malayalam = excluded.malayalam, unit = excluded.unit,
  qty = excluded.qty, opening = excluded.opening,
  total_received = excluded.total_received, total_issued = excluded.total_issued,
  reorder = excluded.reorder, unit_cost = excluded.unit_cost, type = excluded.type;

-- capital_items
insert into capital_items
  (id, name, malayalam, custodian, last_verified, condition, material,
   weight_grams, acquired_year, book_value, current_value)
values
  ('c1', 'Thiruvabharanam — Crown', 'തിരുവാഭരണം', 'Melsanthi', '2026-04-20', 'Excellent', 'Gold', 1850, 1987, 450000, 18500000),
  ('c2', 'Silver Lamp Set (5)', 'വെള്ളി വിളക്ക്', 'Kazhakam', '2026-04-15', 'Good', 'Silver', 4200, 2003, 85000, 480000),
  ('c3', 'Brass Uruli (large)', 'ഉരുളി', 'Oottupura', '2026-04-22', 'Good', 'Brass', 12000, 1995, 18000, 35000),
  ('c4', 'Kalasham (silver)', 'കലശം', 'Melsanthi', '2026-04-20', 'Excellent', 'Silver', 850, 2010, 42000, 98000),
  ('c5', 'Thidambu (deity carrier)', 'തിടമ്പ്', 'Kazhakam', '2026-04-10', 'Good', 'Wood + Gold leaf', 8500, 1972, 25000, 180000)
on conflict (id) do update set
  name = excluded.name, malayalam = excluded.malayalam, custodian = excluded.custodian,
  last_verified = excluded.last_verified, condition = excluded.condition,
  material = excluded.material, weight_grams = excluded.weight_grams,
  acquired_year = excluded.acquired_year, book_value = excluded.book_value,
  current_value = excluded.current_value;

-- retail_items
insert into retail_items
  (id, name, malayalam, brand, category, pack_size, barcode, mrp, cost_price,
   counter_qty, counter_reorder, hsn)
values
  ('r1', 'Camphor Packet 50g', 'കർപ്പൂരം', 'Mangalam', 'Pooja Items', '50 g', '8901234567001', 45, 38, 60, 15, '33074100'),
  ('r2', 'Camphor Tablet 100g', 'കർപ്പൂരം', 'Cycle', 'Pooja Items', '100 g', '8901234567002', 80, 68, 35, 10, '33074100'),
  ('r3', 'Sandal Agarbathi', 'ചന്ദന തിരി', 'Cycle Pure', 'Pooja Items', '30 sticks', '8901234567003', 60, 50, 80, 20, '33074100'),
  ('r4', 'Sambrani Cups', 'സാംബ്രാണി', 'Mysore Sandal', 'Pooja Items', '12 pcs', '8901234567004', 50, 42, 45, 12, '33074100'),
  ('r5', 'Rose Agarbathi', 'ചന്ദന തിരി', 'Mangalam', 'Pooja Items', '20 sticks', '8901234567005', 30, 24, 70, 20, '33074100'),
  ('r6', 'Charadu (Yellow)', 'മഞ്ഞ ചരട്', '—', 'Charadu', '1 nos', '', 10, 6, 200, 50, ''),
  ('r7', 'Charadu (Red)', 'ചുവന്ന ചരട്', '—', 'Charadu', '1 nos', '', 10, 6, 180, 50, ''),
  ('r8', 'Rudraksha Mala', 'രുദ്രാക്ഷം', 'Devi Stores', 'Charadu', '108 beads', '8901234567008', 250, 180, 25, 5, '71179090'),
  ('r9', 'Brass Lamp (Small)', 'വിളക്ക്', 'Kerala Crafts', 'Souvenirs', '1 nos', '8901234567009', 350, 220, 12, 3, '74199100'),
  ('r10', 'Devi Photo Frame (8x10)', 'ഫോട്ടോ', 'Sree Arts', 'Souvenirs', '1 nos', '8901234567010', 180, 110, 18, 5, '44140000'),
  ('r11', 'Sree Yantra (Copper)', 'ശ്രീ യന്ത്രം', 'Vedic Crafts', 'Souvenirs', '1 nos', '8901234567011', 450, 290, 8, 2, '74199900'),
  ('r12', 'Prasadam Box (Med)', 'പ്രസാദ പെട്ടി', '—', 'Souvenirs', '1 nos', '', 25, 12, 100, 25, '48191010')
on conflict (id) do update set
  name = excluded.name, malayalam = excluded.malayalam, brand = excluded.brand,
  category = excluded.category, pack_size = excluded.pack_size,
  barcode = excluded.barcode, mrp = excluded.mrp, cost_price = excluded.cost_price,
  counter_qty = excluded.counter_qty, counter_reorder = excluded.counter_reorder,
  hsn = excluded.hsn;

-- inventory_movements: synthetic 'opening' rows so a future qty-as-view works.
insert into inventory_movements (item_id, delta, reason, source_type, notes)
select id, opening, 'opening', 'manual', 'Seeded opening balance'
from inventory_items
on conflict do nothing;
